lfcc:
  fs: 16000
  num_ceps: 40
  pre_emph: 0
  pre_emph_coeff: 0.97
  win_len: 0.040
  win_hop: 0.020
  win_type: "hamming"
  nfilts: 70
  nfft: 1024
  low_freq: 0
  high_freq: 8000
  scale: "constant"
  dct_type: 2
  normalize: 0
  order_deltas: 2

model:
  name: "LCNN"
  feat_len: 30
  batch_size: 32
  n_input: 1
  n_output: 3
  lr: 0.001
  weight_decay: 0.0001
  n_epoch: 50
  padding_type: "zero"
  params:
    num_conv_layers: 2
    num_channels: 32
    kernel_size: 3
    num_linear_layers: 2
    hidden_size: 128
    num_classes: 3
    stride: 1
    h_in: 30 # feat_len
    w_in: 120 # num_ceps*(order_deltas+1)